function reportFile = DdGeneration_AI(modelPath, varargin)
% DdGeneration_AI  Generate a detailed design document (SDD) driven by the
%   Agentic Toolkit knowledge base produced by analyzeModelDeepForSDD.m.
%
%   The knowledge base JSON contains deep per-subsystem analysis: I/O contracts,
%   internal block logic, calibration parameters and model-read expressions. This
%   script turns that structured data into a compliant Detail Design document with
%   minimal manual authoring — every description is derived from the model itself.
%
%   Inputs:
%       modelPath  - Model file path (e.g. 'Foc_2024b.slx')
%       varargin   - Name/Value:
%           'KnowledgeFile'  - Path to _model_knowledge.json (default: auto-located)
%           'ExcelFile'      - Interface/calibration Excel (optional)
%           'OutputDir'      - Report output directory (default: model dir)
%           'Format'         - 'markdown' (default) | 'pdf'
%
%   Outputs:
%       reportFile - Path to generated report
%
%   Usage:
%       DdGeneration_AI('Foc_2024b.slx');
%       DdGeneration_AI('Foc_2024b.slx', 'ExcelFile', 'Foc_interface.xlsx', 'Format', 'pdf');
%
%   Two-phase workflow (see also runAISDD.m):
%       1. analyzeModelDeepForSDD('Model.slx');          % builds knowledge JSON
%       2. DdGeneration_AI('Model.slx');                 % renders the SDD

    fprintf('=== AI-Driven Detail Design Generation ===\n\n');

    %% ---- Parse inputs ----
    p = inputParser;
    addRequired(p, 'modelPath', @(x) ischar(x) || isstring(x));
    addParameter(p, 'KnowledgeFile', '', @ischar);
    addParameter(p, 'ExcelFile', '', @ischar);
    addParameter(p, 'OutputDir', '', @ischar);
    addParameter(p, 'Format', 'markdown', @(x) any(strcmpi(x, {'markdown','pdf'})));
    parse(p, modelPath, varargin{:});

    modelPath = char(p.Results.modelPath);
    knowledgeFile = char(p.Results.KnowledgeFile);
    excelFile = char(p.Results.ExcelFile);
    outDir = char(p.Results.OutputDir);
    fmt = lower(char(p.Results.Format));

    [mdir, modelBase, ~] = fileparts(modelPath);
    if isempty(mdir), mdir = pwd; end
    if isempty(modelBase), modelBase = modelPath; end
    if isempty(outDir), outDir = mdir; end
    if ~exist(outDir, 'dir'), mkdir(outDir); end

    %% ---- Locate knowledge base ----
    if isempty(knowledgeFile)
        candidate = fullfile(mdir, [modelBase '_model_knowledge.json']);
        if ~isfile(candidate)
            error(['Knowledge base not found: %s\n' ...
                'Run analyzeModelDeepForSDD(''%s'') first, or pass KnowledgeFile.'], ...
                candidate, modelPath);
        end
        knowledgeFile = candidate;
    end

    %% ---- Load knowledge ----
    kb = jsondecode(fileread(knowledgeFile));
    fprintf('Loaded knowledge base: %s\n', knowledgeFile);
    fprintf('  Model: %s, Subsystems: %d\n', kb.model, numel(kb.subsystems));

    %% ---- Load Excel interface/calibration if provided ----
    iface = struct(); cal = struct();
    if ~isempty(excelFile) && isfile(excelFile)
        try
            [iface, cal] = readInterfaceWorkbookAI(excelFile);
            fprintf('Loaded Excel interface/calibration: %s\n', excelFile);
        catch ME
            fprintf('⚠ Excel load failed (continuing with model data): %s\n', ME.message);
        end
    end

    %% ---- Render ----
    switch fmt
        case 'pdf'
            reportFile = renderPDF(kb, iface, cal, outDir);
        otherwise
            reportFile = renderMarkdown(kb, iface, cal, outDir);
    end

    fprintf('\n=== Report Generated ===\n');
    fprintf('%s\n', reportFile);
end

%% =====================================================================
function mdFile = renderMarkdown(kb, iface, cal, outDir)
    modelName = kb.model;
    mdFile = fullfile(outDir, [modelName '_DetailDesign.md']);

    fid = fopen(mdFile, 'w');
    w = @(fmt, varargin) fprintf(fid, fmt, varargin{:});

    % Header / title
    w('# %s — Detail Design (AI-Generated)\n\n', modelName);
    w('| | |\n|---|---|\n');
    w('| Generated by | `DdGeneration_AI` + `analyzeModelDeepForSDD` |\n');
    w('| Generated at | %s |\n', kb.generatedAt);
    if isfield(kb, 'config')
        cfg = kb.config;
        if isfield(cfg, 'solver')
            w('| Solver | `%s`, FixedStep=`%s`, StopTime=`%s` |\n', ...
                cfg.solver, cfg.fixedStep, cfg.stopTime);
        end
    end
    w('\n');

    % Table of contents
    w('## 目录\n\n');
    w('- [1. 概述](#1-概述)\n');
    w('- [2. 顶层接口](#2-顶层接口)\n');
    w('- [3. 标定参数](#3-标定参数)\n');
    w('- [4. 子系统详细设计](#4-子系统详细设计)\n');
    for i = 1:numel(kb.subsystems)
        s = kb.subsystems(i);
        anchor = matlab.lang.makeValidName(s.name);
        w('  - [%d.%d %s](#%s)\n', 4, i, s.name, lower(anchor));
    end
    w('\n');

    %% Section 1: Overview
    w('## 1. 概述\n\n');
    if isfield(kb, 'overview') && ~isempty(kb.overview)
        w('```\n%s\n```\n\n', kb.overview);
    end

    %% Section 2: Top-level interfaces
    w('## 2. 顶层接口\n\n');
    w('### 2.1 输入信号\n\n');
    renderPortTable(w, kb.interfaces.inputs);
    w('\n### 2.2 输出信号\n\n');
    renderPortTable(w, kb.interfaces.outputs);

    %% Section 3: Calibration parameters
    w('\n## 3. 标定参数\n\n');
    w('| 标定名 | 所属模块 | 参数 |\n|---|---|---|\n');
    calCount = 0;
    for i = 1:numel(kb.subsystems)
        cals = kb.subsystems(i).calibrations;
        for j = 1:numel(cals)
            w('| `%s` | `%s` | `%s` |\n', cals(j).name, ...
                cals(j).block, cals(j).param);
            calCount = calCount + 1;
        end
    end
    if calCount == 0
        w('_(未在模型中检测到 `cal_*` 标定参数)_\n');
    end

    %% Section 4: Subsystem detailed design
    w('\n## 4. 子系统详细设计\n\n');
    for i = 1:numel(kb.subsystems)
        s = kb.subsystems(i);
        w('### 4.%d %s\n\n', i, s.name);

        % Description
        w('**功能描述：** %s\n\n', s.description);

        % I/O contract
        w('**输入：** ');
        if isempty(s.inputs)
            w('—\n');
        else
            w('%s\n', strjoin(arrayfun(@(x) sprintf('`%s`(%s)', x.name, x.dataType), s.inputs, 'UniformOutput', false), ', '));
        end
        w('\n**输出：** ');
        if isempty(s.outputs)
            w('—\n');
        else
            w('%s\n', strjoin(arrayfun(@(x) sprintf('`%s`(%s)', x.name, x.dataType), s.outputs, 'UniformOutput', false), ', '));
        end
        w('\n');

        % Internal blocks
        if ~isempty(s.blocks)
            w('**内部模块：**\n\n');
            w('| 模块 | 类型 | 关键参数 |\n|---|---|---|\n');
            for j = 1:numel(s.blocks)
                ptext = '';
                fn = fieldnames(s.blocks(j).params);
                for k = 1:numel(fn)
                    ptext = [ptext, sprintf('`%s`=%s ', fn{k}, ... %#ok<AGROW>
                        mat2str(double(s.blocks(j).params.(fn{k})), 6))]; %#ok<AGROW>
                end
                w('| `%s` | `%s` | %s |\n', s.blocks(j).name, s.blocks(j).type, ptext);
            end
            w('\n');
        end

        % Calibrations
        if ~isempty(s.calibrations)
            w('**标定参数：** ');
            w('%s\n\n', strjoin(arrayfun(@(x) sprintf('`%s`', x.name), s.calibrations, 'UniformOutput', false), ', '));
        end

        % Model-read expression (algorithm traceability)
        if isfield(s, 'modelRead') && ~isempty(s.modelRead)
            w('<details><summary>模型读取表达式（algorithm traceability）</summary>\n\n');
            w('```\n%s\n```\n\n</details>\n\n', s.modelRead);
        end
    end

    fclose(fid);
end

%% =====================================================================
function renderPortTable(w, ports)
    if isempty(ports)
        w('_(无)_\n');
        return;
    end
    w('| 信号名 | 数据类型 | Min | Max | 描述 |\n|---|---|---|---|---|\n');
    for i = 1:numel(ports)
        w('| `%s` | `%s` | %s | %s | %s |\n', ...
            ports(i).name, ports(i).dataType, ...
            ports(i).min, ports(i).max, ports(i).description);
    end
end

%% =====================================================================
function pdfFile = renderPDF(kb, iface, cal, outDir)
% Render a PDF via the MATLAB Report Generator if available.
    modelName = kb.model;
    pdfBase = fullfile(outDir, [modelName '_DetailDesign_AI']);
    rpt = slreportgen.report.Report(pdfBase, 'pdf');
    rpt.CompileModelBeforeReporting = false;

    tp = mlreportgen.report.TitlePage;
    tp.Title = modelName + " Detail Design (AI-Generated)";
    tp.Subtitle = "Generated by analyzeModelDeepForSDD + DdGeneration_AI";
    append(rpt, tp);
    append(rpt, mlreportgen.report.TableOfContents);

    % Overview
    sec = mlreportgen.report.Section;
    sec.Title = "Model Overview";
    append(sec, mlreportgen.dom.Paragraph(string(kb.overview)));
    append(rpt, sec);

    % Interfaces
    if ~isempty(kb.interfaces.inputs)
        append(rpt, interfaceSection('Input Signals', kb.interfaces.inputs));
    end
    if ~isempty(kb.interfaces.outputs)
        append(rpt, interfaceSection('Output Signals', kb.interfaces.outputs));
    end

    % Subsystems
    for i = 1:numel(kb.subsystems)
        s = kb.subsystems(i);
        sec = mlreportgen.report.Section;
        sec.Title = sprintf('Subsystem %d: %s', i, s.name);
        append(sec, mlreportgen.dom.Paragraph(string(s.description)));
        if ~isempty(s.blocks)
            append(sec, mlreportgen.dom.Paragraph("Internal blocks:"));
            names = arrayfun(@(x) sprintf('%s (%s)', x.name, x.type), s.blocks, 'UniformOutput', false);
            append(sec, mlreportgen.dom.Paragraph(strjoin(names, ', ')));
        end
        append(rpt, sec);
    end

    close(rpt);
    pdfFile = pdfBase + ".pdf";
end

%% =====================================================================
function sec = interfaceSection(title, ports)
    sec = mlreportgen.report.Section;
    sec.Title = title;
    t = mlreportgen.dom.Table(numel(ports) + 1, 5);
    t.Border = 'solid'; t.ColSep = 'solid'; t.RowSep = 'solid';
    hdr = mlreportgen.dom.TableRow;
    for c = {'Name','DataType','Min','Max','Description'}
        append(hdr, mlreportgen.dom.TableEntry(mlreportgen.dom.Paragraph(c{1})));
    end
    append(t, hdr);
    for i = 1:numel(ports)
        r = mlreportgen.dom.TableRow;
        vals = {ports(i).name, ports(i).dataType, ports(i).min, ports(i).max, ports(i).description};
        for j = 1:5
            append(r, mlreportgen.dom.TableEntry(mlreportgen.dom.Paragraph(vals{j})));
        end
        append(t, r);
    end
    append(sec, t);
end

%% =====================================================================
function [iface, cal] = readInterfaceWorkbookAI(excelPath)
% Lightweight Excel reader for interface + calibration sheets.
    iface = struct(); cal = struct();
    sheets = sheetnames(excelPath);
    sigSheet = '';
    calSheet = '';
    for i = 1:numel(sheets)
        s = lower(sheets(i));
        if contains(s, 'signal') || contains(s, 'interface'), sigSheet = sheets(i); end
        if contains(s, 'cal'), calSheet = sheets(i); end
    end
    if isempty(sigSheet), sigSheet = sheets(1); end
    try
        T = readtable(excelPath, 'Sheet', sigSheet, 'PreserveVariableNames', true);
        iface = T;
    catch
    end
    if ~isempty(calSheet)
        try
            cal = readtable(excelPath, 'Sheet', calSheet, 'PreserveVariableNames', true);
        catch
        end
    end
end
